// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vault.Data.Context;

#nullable disable

namespace Vault.Db.Migrations
{
    [DbContext(typeof(VaultContext))]
    [Migration("20260121161853_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vault.Models.Document", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("id");

                    b.Property<string>("Charset")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("charset");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("bigint")
                        .HasColumnName("content_length");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<DateTime?>("ExtractionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extraction_date");

                    b.Property<byte?>("ExtractionLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("extraction_level");

                    b.Property<string>("Language")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<short?>("NerMask")
                        .HasColumnType("smallint")
                        .HasColumnName("ner_mask");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("path");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("project_id");

                    b.Property<string>("RootId")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("root_id");

                    b.Property<byte?>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("document_parent_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("document_status");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("Vault.Models.NamedEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("category");

                    b.Property<string>("DocId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("doc_id");

                    b.Property<byte>("Extractor")
                        .HasColumnType("smallint")
                        .HasColumnName("extractor");

                    b.Property<string>("ExtractorLanguage")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("extractor_language");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("boolean")
                        .HasColumnName("hidden");

                    b.Property<string>("Mention")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mention");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint")
                        .HasColumnName("ne_offset");

                    b.Property<string>("RootId")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("root_id");

                    b.HasKey("Id");

                    b.HasIndex("DocId")
                        .HasDatabaseName("named_entity_doc_id");

                    b.ToTable("named_entity");
                });

            modelBuilder.Entity("Vault.Models.UserInventory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider");

                    b.HasKey("Id");

                    b.ToTable("user_inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
